import type { Metadata } from "next";
import { Teko, Sigmar } from "next/font/google";
import "./globals.css";

const sigmar = Sigmar({ subsets: ["latin"], weight: "400" });

const teko = Teko({ subsets: ["latin"], weight: "400" });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sigmar.className} ${teko.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
